# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.2
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: 7.2
    - php: hhvm

# Update composer
before-install:
  - composer self-update
  - composer install

# Run script
script:
  - phpunit
