language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.2
  - 7.2.0
  - hhvm

env:
  - TESTER_PHP_BIN="php-cgi"
  - TESTER_PHP_BIN="hhvm"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: 5.3.3
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.4
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.5
      env: TESTER_PHP_BIN="hhvm"

    - php: 5.6
      env: TESTER_PHP_BIN="hhvm"

    - php: 7.2
      env: TESTER_PHP_BIN="hhvm"

    - php: 7.2.0
      env: TESTER_PHP_BIN="hhvm"

    - php: hhvm
      env: TESTER_PHP_BIN="php-cgi"

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

before_script:
  - mysql -u root -e 'CREATE DATABASE feedie_base;'
  - mysql -u root feedie_base < database/feedie_base.sql

after_failure:
  # Prints *.actual files content
  - for i in $(find ./database -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done